### ISSUE TITLE
Building and testing with Github Actions result in compiler errors

### ISSUE THREAD

**Issue by loic-lopez** [microsoft/MSBuildForUnity#141]
I have a project outside of unity which is build by MSBuildForUnity and it works in the Editor but I try to have a CI/CD with Github Actions so there is my .yml config:

```yml
name: UMVC.Editor Tests

on:
  push:
    branches:
      - master
      - release/*
      - staging/*
      - pre-release/*
  pull_request:
    branches: [ master ]


jobs:
  test:
    name: Test UMVC.Editor
    runs-on: ubuntu-latest
    container: gableroux/unity3d:2019.3.13f1
    steps:
      - uses: actions/checkout@v2

      - name: Decrypt the license file
        run: openssl aes-256-cbc -d -in .github/Unity_v2019.x.ulf.enc -k ${{ secrets.UNITY_LICENSE_DECRYPT_KEY }} >> .github/Unity_v2019.x.ulf

      # Activate unity
      - name: Activate Unity
        run: xvfb-run /opt/Unity/Editor/Unity -quit -batchmode -nographics -silent-crashes -logFile -manualLicenseFile .github/Unity_v2019.x.ulf || exit 0

      # Run tests
      - name: Run tests
        run: xvfb-run /opt/Unity/Editor/Unity -quit -batchmode -nographics -logFile -runTests -testPlatform editmode
#  
```

MSBuildForUnity seems to generate the dll in the log:
```
Whole Generate Projects process took 145 ms; actual generation took 144; solution export: 5; exporter creation: 0; props file generation: 138
```

But at the end I'm getting:
```
Scripts have compiler errors. 
(Filename: ./Runtime/Utilities/Argv.cpp Line: 361)


Aborting batchmode due to failure:
Scripts have compiler errors.

/home/builduser/buildslave/unity/build/PlatformDependent/Linux/External/baselib/builds/Include/C/Baselib_ThreadLocalStorage.inl.h(12): Assertion failed (rc == 0)
Caught fatal signal - signo:5 code:128 errno:0 addr:(nil)
/home/builduser/buildslave/unity/build/PlatformDependent/Linux/External/baselib/builds/Include/C/Baselib_ThreadLocalStorage.inl.h(12): Assertion failed (rc == 0)
Caught fatal signal - signo:5 code:128 errno:0 addr:(nil)
[Unity Package Manager (Upm)]
Parent process [105] was terminated
##[error]Process completed with exit code 1.
```
As if an AssetDatabase.Refresh is missing after building.

- **MSBuildForUnity version:** 0.9.2-20200131.11
- **Unity version:** 2019.3.13f1

**You can see the full log at:** https://github.com/loic-lopez/UMVC/runs/670096612?check_suite_focus=true
