### ISSUE TITLE
UnityMetaFileGenerator.targets does not generate .meta file compatible for Unity 2019 LTS (e.g. Asset library 2.0)

### ISSUE THREAD

**Issue by hendryems** [microsoft/MSBuildForUnity#146]
With Unity 2019 LTS/introduction of the new asset library, it look like the .meta file generated by MSBuildForUnity contains extraneous linebreaks that the YAML parser in Unity no longer expects.

Before (no longer recognized):
```
fileFormatVersion: 2
guid: beddd2171b0a2d63e917dd0a6fd71e4a
PluginImporter:
  serializedVersion: 2
  platformData:

  - first:
      Editor: Editor
    second:
      enabled: 1
      settings: {}
  executionOrder: {}
```

Expected (notice no line breaks after `platformData`):
```
fileFormatVersion: 2
guid: beddd2171b0a2d63e917dd0a6fd71e4a
PluginImporter:
  serializedVersion: 2
  platformData:
  - first:
      Editor: Editor
    second:
      enabled: 1
      settings: {}
  executionOrder: {}
```

Fix should be:
![image](https://user-images.githubusercontent.com/50596066/118572846-33328d00-b736-11eb-935a-292555d046c0.png)
